server:
  port: 8080
  servlet:
    context-path: /demo
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/xx?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: heru
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
      throw-exception-if-no-handler-found: true
      view:
        prefix: /
        suffix: .html
    devtools:
      restart:
        enabled: true
    profiles:
      active: mybatis, schedule

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath*:/com/**/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.pf.**.entity  # 注意：对应实体类的路径
#pagehelper分页插件
pagehelper:
    helper-dialect: mysql
logging:
  level:
    com.pf: debug
